const CONFIGS = {
  BOARD_WIDTH: 512,
  BOARD_HEIGHT: 448,
  CHARACTER_WIDTH: 18,
  CHARACTER_HEIGHT: 21,
  STAGE_FLOOR_HEIGHT: 32,
  ELEVATOR_WIDTH: 30,
  ELEVATOR_HEIGHT: 12,
  GRAVITY: 0.25,
  MARIO_JUMP: 7.5,
  //LOGO SETTINGS
  LOGO_WIDTH: 414,
  LOGO_HEIGHT: 238,
  LIVE_WIDTH: 20,
  LIVE_HEIGHT: 12,
  PLAYER_LIVES: 5
}

export default CONFIGS